export const RECEIVE_LISTS = 'RECEIVE_LISTS';
export const RECEIVE_BY_QUERYSTRING = 'RECEIVE_BY_QUERYSTRING';
export const RECEIVE_USERS_BY_LIST = 'RECEIVE_USERS_BY_LIST';
export const RECEIVE_PRODUTS_BY_LIST = 'RECEIVE_PRODUTS_BY_LIST';
export const RECEIVE_USERS_BY_FAMILY = 'RECEIVE_USERS_BY_FAMILY';
export const RECEIVE_PRODUTS = 'RECEIVE_PRODUTS';
export const REQUEST_CONTACTS = 'REQUEST_CONTACTS';
export const REQUEST_LISTS = 'REQUEST_LISTS';
export const RECEIVE_DELETE_PRODUTS = 'RECEIVE_DELETE_PRODUTS';
export const DELETE_LISTS = 'DELETE_LISTS';
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_EDIT_PRODUTS = 'RECEIVE_EDIT_PRODUTS';
export const RECEIVE_EDIT_LISTS = 'RECEIVE_EDIT_LISTS';




