export const REQUEST_CONTACTS = 'REQUEST_CONTACTS';
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';

export const REQUEST_CONTACT_BY_ID = 'REQUEST_CONTACT_BY_ID';
export const RECEIVE_CONTACT_BY_ID = 'RECEIVE_CONTACT_BY_ID';
